# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import raft_pb2 as raft__pb2


class RaftStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.request_vote = channel.unary_unary(
                '/Raft/request_vote',
                request_serializer=raft__pb2.Vote.SerializeToString,
                response_deserializer=raft__pb2.Bulletin.FromString,
                )
        self.append_entries = channel.unary_unary(
                '/Raft/append_entries',
                request_serializer=raft__pb2.Systole.SerializeToString,
                response_deserializer=raft__pb2.Diastole.FromString,
                )
        self.get_leader = channel.unary_unary(
                '/Raft/get_leader',
                request_serializer=raft__pb2.Empty.SerializeToString,
                response_deserializer=raft__pb2.ServerInfo.FromString,
                )
        self.suspend = channel.unary_unary(
                '/Raft/suspend',
                request_serializer=raft__pb2.Period.SerializeToString,
                response_deserializer=raft__pb2.Empty.FromString,
                )


class RaftServicer(object):
    """Missing associated documentation comment in .proto file."""

    def request_vote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def append_entries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_leader(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def suspend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RaftServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'request_vote': grpc.unary_unary_rpc_method_handler(
                    servicer.request_vote,
                    request_deserializer=raft__pb2.Vote.FromString,
                    response_serializer=raft__pb2.Bulletin.SerializeToString,
            ),
            'append_entries': grpc.unary_unary_rpc_method_handler(
                    servicer.append_entries,
                    request_deserializer=raft__pb2.Systole.FromString,
                    response_serializer=raft__pb2.Diastole.SerializeToString,
            ),
            'get_leader': grpc.unary_unary_rpc_method_handler(
                    servicer.get_leader,
                    request_deserializer=raft__pb2.Empty.FromString,
                    response_serializer=raft__pb2.ServerInfo.SerializeToString,
            ),
            'suspend': grpc.unary_unary_rpc_method_handler(
                    servicer.suspend,
                    request_deserializer=raft__pb2.Period.FromString,
                    response_serializer=raft__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Raft', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Raft(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def request_vote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Raft/request_vote',
            raft__pb2.Vote.SerializeToString,
            raft__pb2.Bulletin.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def append_entries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Raft/append_entries',
            raft__pb2.Systole.SerializeToString,
            raft__pb2.Diastole.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_leader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Raft/get_leader',
            raft__pb2.Empty.SerializeToString,
            raft__pb2.ServerInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def suspend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Raft/suspend',
            raft__pb2.Period.SerializeToString,
            raft__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
