# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chord.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63hord.proto\"\x1a\n\x07\x41\x64\x64ress\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"(\n\x07IdReply\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tm_message\x18\x02 \x01(\t\"\x10\n\x02Id\x12\n\n\x02id\x18\x01 \x01(\r\"8\n\x03Ids\x12\x1b\n\x13predecessor_address\x18\x01 \x01(\t\x12\x14\n\x0crequired_ids\x18\x02 \x03(\r\"/\n\tBoolReply\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x12\n\nid_message\x18\x02 \x01(\t\"\'\n\x08NodeInfo\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\"\'\n\x0b\x46ingerTable\x12\x18\n\x05table\x18\x01 \x03(\x0b\x32\t.NodeInfo\"N\n\x0fPopFingTableRep\x12\x1e\n\x0bpredecessor\x18\x01 \x01(\x0b\x32\t.NodeInfo\x12\x1b\n\x05table\x18\x02 \x01(\x0b\x32\x0c.FingerTable\"\x07\n\x05\x45mpty\"&\n\nServerType\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\r\"!\n\x04\x44\x61ta\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"\x12\n\x03Key\x12\x0b\n\x03key\x18\x01 \x01(\t2\xcb\x01\n\x08Registry\x12 \n\x08register\x12\x08.Address\x1a\x08.IdReply\"\x00\x12\x1f\n\nderegister\x12\x03.Id\x1a\n.BoolReply\"\x00\x12\x30\n\x15populate_finger_table\x12\x03.Id\x1a\x10.PopFingTableRep\"\x00\x12(\n\x0eget_chord_info\x12\x06.Empty\x1a\x0c.FingerTable\"\x00\x12 \n\x07get_ack\x12\x06.Empty\x1a\x0b.ServerType\"\x00\x32\xcb\x01\n\x04Node\x12*\n\x10get_finger_table\x12\x06.Empty\x1a\x0c.FingerTable\"\x00\x12\x1b\n\x04save\x12\x05.Data\x1a\n.BoolReply\"\x00\x12\x1c\n\x06remove\x12\x04.Key\x1a\n.BoolReply\"\x00\x12\x1a\n\x04\x66ind\x12\x04.Key\x1a\n.BoolReply\"\x00\x12\x1e\n\x0csave_to_pred\x12\x04.Ids\x1a\x06.Empty\"\x00\x12 \n\x07get_ack\x12\x06.Empty\x1a\x0b.ServerType\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chord_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADDRESS._serialized_start=15
  _ADDRESS._serialized_end=41
  _IDREPLY._serialized_start=43
  _IDREPLY._serialized_end=83
  _ID._serialized_start=85
  _ID._serialized_end=101
  _IDS._serialized_start=103
  _IDS._serialized_end=159
  _BOOLREPLY._serialized_start=161
  _BOOLREPLY._serialized_end=208
  _NODEINFO._serialized_start=210
  _NODEINFO._serialized_end=249
  _FINGERTABLE._serialized_start=251
  _FINGERTABLE._serialized_end=290
  _POPFINGTABLEREP._serialized_start=292
  _POPFINGTABLEREP._serialized_end=370
  _EMPTY._serialized_start=372
  _EMPTY._serialized_end=379
  _SERVERTYPE._serialized_start=381
  _SERVERTYPE._serialized_end=419
  _DATA._serialized_start=421
  _DATA._serialized_end=454
  _KEY._serialized_start=456
  _KEY._serialized_end=474
  _REGISTRY._serialized_start=477
  _REGISTRY._serialized_end=680
  _NODE._serialized_start=683
  _NODE._serialized_end=886
# @@protoc_insertion_point(module_scope)
